---
# PLAY *****************************************************************************************************************
- name: Terraform
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Terraform
      block:
        - name: 'Terraform plan GitHub Enterprise Server HA ({{ terraform_workspace }})'
          # https://docs.ansible.com/ansible/latest/collections/community/general/terraform_module.html
          community.general.terraform:
            project_path: '../terraform/ghes'
            variables_file: '../vars/{{ terraform_workspace }}.tfvars'
            state: planned
            plan_file: './terraform.tfstate.d/{{ terraform_workspace }}/terraform.tfplan'
            workspace: '{{ terraform_workspace }}'
          tags:
            - ghes
            - ha

        - name: 'Terraform plan GitHub Enterprise Server backup-utils ({{ terraform_workspace }})'
          # https://docs.ansible.com/ansible/latest/collections/community/general/terraform_module.html
          community.general.terraform:
            project_path: '../terraform/backup-utils'
            variables_file: '../vars/{{ terraform_workspace }}.tfvars'
            state: planned
            plan_file: './terraform.tfstate.d/{{ terraform_workspace }}/terraform.tfplan'
            workspace: '{{ terraform_workspace }}'
          tags:
            - backup

      # https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#ansible-no-log
      # we do not log to not expose sensitive data
      no_log: true
