---
all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    # we use this field to store messages to display at the end of a play
    messages: []
  children:
    localhost:
      vars:
        ansible_user: root
        ansible_connection: local
    ghes:
      vars:
        ansible_port: 122
      hosts:
        primary:
          ansible_host: 0.0.0.0
        replica:
          ansible_host: 0.0.0.0
        georeplica:
          ansible_host: 0.0.0.0
    utils:
      vars:
        ansible_port: 22
      hosts:
        backup:
          ansible_host: 0.0.0.0
        monitoring:
          ansible_host: 0.0.0.0
