on:
  push:
    paths:
      - 'ansible/**/*'

name: Ansible Lint

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install ansible ansible-lint
      - name: ansible-lint
        run: |
          cd ansible
          ansible-lint *.yml -c .ansible-lint
